webdev:
  restart: always
  build: .
  ports:
    - "5000:5000"
    - "8080:8080"
    - "8888:8888"
    - "2222:22"
  links:
    - postgres
  volumes:
    - ./data/works:/home/tomohitoy/works

postgres:
  restart: always
  image: postgres
  environment:
    POSTGRES_USER: tomohitoy
    POSTGRES_PASSWORD: tomohitoy
  ports:
    - "5432:5432"
  volumes:
    - ./data/postgresql:/var/lib/postgresql/data
